vector<Program *> generateTestPrograms(){
  return vector<Program *>{
        new Program(FacultyType::ComputerScience, City::Ismailia, 1, UniversityType::Public,
                    University::SuezCanalUniversity, 5, mathGradePriority),
        new Program(FacultyType::Science, City::Ismailia, 1, UniversityType::Public, University::SuezCanalUniversity, 5,
                    scienceGradePriority),
        new Program(FacultyType::Education, City::Ismailia, 1, UniversityType::Public, University::SuezCanalUniversity,
                    5, arabicGradePriority),
        new Program(FacultyType::Engineering, City::Ismailia, 1, UniversityType::Public,
                    University::SuezCanalUniversity, 5, englishGradePriority),
        new Program(FacultyType::Medicine, City::Ismailia, 1, UniversityType::Public, University::SuezCanalUniversity,
                    5, mathAndScienceWeightedPriority),
        new Program(FacultyType::ComputerScience, City::PortSaid, 5, UniversityType::Public,
                    University::PortSaidUniversity, 5, mathGradePriority),
        new Program(FacultyType::Science, City::PortSaid, 5, UniversityType::Public, University::PortSaidUniversity, 5,
                    scienceGradePriority),
        new Program(FacultyType::Education, City::PortSaid, 5, UniversityType::Public, University::PortSaidUniversity,
                    5, arabicGradePriority),
        new Program(FacultyType::Engineering, City::PortSaid, 5, UniversityType::Public, University::PortSaidUniversity,
                    5, englishGradePriority),
        new Program(FacultyType::Medicine, City::PortSaid, 5, UniversityType::Public, University::PortSaidUniversity, 5,
                    mathAndScienceWeightedPriority),
        new Program(FacultyType::ComputerScience, City::Cairo, 2, UniversityType::Public, University::CairoUniversity,
                    5, mathGradePriority),
        new Program(FacultyType::Science, City::Cairo, 2, UniversityType::Public, University::CairoUniversity, 5,
                    scienceGradePriority),
        new Program(FacultyType::Education, City::Cairo, 2, UniversityType::Public, University::CairoUniversity, 5,
                    arabicGradePriority),
        new Program(FacultyType::Engineering, City::Cairo, 2, UniversityType::Public, University::CairoUniversity, 5,
                    englishGradePriority),
        new Program(FacultyType::Medicine, City::Cairo, 2, UniversityType::Public, University::CairoUniversity, 5,
                    mathAndScienceWeightedPriority)
    };
}